# Generated by Django 3.2.5 on 2021-11-16 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_person_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
